[workspace]
authors = ["Jainam Jadav <jainamjadav1673@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "mojo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = "==0.25.6"
